```{r}
library(rstan)
library(tidyr)
library(dplyr)
library(readr)

rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
```

```{r}
data <- read_csv('../data/Rep12_MOB_46.csv')
data <- data %>% separate(X1, c('x', 'y'), 'x', convert = TRUE)
```
```{r}
data
```


```{r}
qplot(data$x, data$y, color = log10(data$Cdk13 + 1), size = 20)
```

```{r}
gpr <- stan_model('gp_regression.stan')
```

```{r}
1
```


```{r}
temp_data <- list(N = nrow(data),
                 x = as.matrix(data[, c('x', 'y')]),
                 y = log10(data$Cdk13 + 1))

opt <- optimizing(object = gpr, data = temp_data)
```

```{r}
print(opt$par)
```

```{r}
for (g in colnames(subset(data, select = -c(x, y))))
{
  y = log10(data + 1)[,g]
  temp_data <- list(N = nrow(data),
                   x = as.matrix(data[, c('x', 'y')]),
                   y = y)
  sink('/dev/null')
  opt <- optimizing(object = gpr, data = temp_data)
  sink()
  print(opt$par)
}
```

```{r}

```

```{r}
data$Cdk13
```

```{r}
as.numeric(data['Cdk13'])
```


```{r}


```

```{r}
log10(data + 1)
```




