from glob import glob

files = glob('../data/*.csv')
files = map(os.path.basename, files)
files = map(lambda s: s.replace('.csv', '_gp_stats.csv'), files)

rule all:
    input: list(files)

rule fit_gps:
    input:
        '../data/{gene_batch}.csv'
    output:
        '{gene_batch}_gp_stats.csv'
    shell:
        ''' python fit_gps.py {input} {output}
        '''
