import os

results = [
    '100/sim_spatialde_time.csv', 
    '250/sim_spatialde_time.csv',
    '500/sim_spatialde_time.csv', 
    '1000/sim_spatialde_time.csv',
    '2000/sim_spatialde_time.csv',
    '100/sim_stan_time.csv', 
    '250/sim_stan_time.csv',
    '500/sim_stan_time.csv',
    '1000/sim_stan_time.csv',
    '2000/sim_stan_time.csv'
]

rule all:
    input:
        results

rule spatialde:
    input:
        '{size}/sim',
    output:
        '{size}/sim_spatialde_time.csv'
    shell:
        'python run_spatialde.py {input}'

rule stan:
    input:
        '{size}/sim',
    output:
        '{size}/sim_stan_time.csv'
    shell:
        'python run_stan.py {input}'

rule make_data:
    output:
        '{size}/sim'
    shell:
        'python simulate_data {output} {wildcards.size} 10000 &&'
        'touch {output}'

